(add-hook 'dired-mode-hook
          '(lambda ()
             (define-key dired-mode-map [tab] 'dired-hide-subdir)
             (define-key dired-mode-map "q" 'kill-buffer)
             (define-key dired-mode-map "e" 'dired-open-eshell)
             (define-key dired-mode-map "p" 'dired-up-directory)
             (define-key dired-mode-map "n" 'dired-advertised-find-file)
             (define-key dired-mode-map "j" 'dired-next-line)
             (define-key dired-mode-map "k" 'dired-previous-line)
             (define-key dired-mode-map "v" 'dired-open-with-evince)))

(defun dired-open-eshell ()
  (interactive)  
  (let ((current-dir dired-directory))
    (eshell)
    (eshell-kill-input)
    (cd current-dir)
    (eshell-send-input)))

(defun dired-open-current-directory ()
  (interactive)
  (dired "."))

(defun dired-open-with-evince ()
  (interactive)
  (dired-do-shell-command evince))