(add-to-list 'auto-mode-alist '("\\.erb$" . html-mode))
(add-to-list 'auto-mode-alist '("\\.stumpwmrc$" . lisp-mode))
(when (require 'markdown-mode nil t)
  (add-to-list 'auto-mode-alist '("\.md$" . markdown-mode))
  (add-to-list 'auto-mode-alist '("\.markdown$" . markdown-mode)))
(when (require 'apache-mode nil t)
  (add-to-list 'auto-mode-alist '("\\.htaccess\\'"   . apache-mode))
  (add-to-list 'auto-mode-alist '("https?d\\.conf\\'"  . apache-mode))
  (add-to-list 'auto-mode-alist '("srm\\.conf\\'"    . apache-mode))
  (add-to-list 'auto-mode-alist '("access\\.conf\\'" . apache-mode))
  (add-to-list 'auto-mode-alist '("sites-\\(available\\|enabled\\)/" . apache-mode)))

(provide 'my-auto-mode-mapping)
