(setq auto-mode-alist (cons '("\\.ssp$" . html-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.jsp$" . html-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.jspx$" . html-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.tagx$" . html-mode) auto-mode-alist))
(add-hook 'sgml-mode-hook (lambda ()
                   (define-key html-mode-map (kbd "C-c C-j") 'jaunte)
                   (setq sgml-basic-offset 4)))
