(global-set-key (kbd "C-x r l") 'anything-bookmarks)
(global-set-key (kbd "<f12>") 'shell-pop)
(global-set-key (kbd "M-k") 'delete-line)
(global-set-key (kbd "C-h") 'delete-backward-char)
(global-set-key (kbd "M-h") 'help)
(global-set-key (kbd "<up>") 'sane-previous-line)
(global-set-key (kbd "<down>") 'sane-next-line)
(global-set-key (kbd "C-m") 'sane-newline)
(global-set-key (kbd "C-S-n") 'forward-paragraph)
(global-set-key (kbd "C-S-p") 'backward-paragraph)
(global-set-key (kbd "<f2>") 'other-window)
(global-set-key (kbd "C-x r l") 'anything-bookmarks)
(global-set-key (kbd "C-l") 'anything)
(global-set-key (kbd "M-y") 'anything-show-kill-ring)
(global-set-key (kbd "C-x C-d") 'anything-current-dir)
(global-set-key (kbd "C-x C-i") 'anything-imenu)
(global-set-key (kbd "C-x C-b") 'anything-buffers+)
(global-set-key (kbd "C-x p") 'anything-project)
(global-set-key (kbd "C-x w") 'anything-my-moin)
(global-set-key (kbd "M-s o") 'occur-by-moccur)
(global-set-key (kbd "C-c v") 'svn-status)
(global-set-key (kbd "C-c d") 'flymake-display-err-menu-for-current-line)
(global-set-key (kbd "C-x t") 'twit)
(global-set-key (kbd "C-x C-t") 'twittering-update-status-interactive)
(global-set-key (kbd "C-x g") 'google)
(global-set-key (kbd "C-S-p") 'windmove-up)
(global-set-key (kbd "C-S-n") 'windmove-down)
(global-set-key (kbd "C-S-f") 'windmove-right)
(global-set-key (kbd "C-S-B") 'windmove-left)
(global-set-key (kbd "<f12>") 'shell-pop)
(global-set-key (kbd "C-<tab>") 'hs-toggle-hiding)
(global-set-key (kbd "M-SPC") 'bm-toggle)
(global-set-key (kbd "M-[") 'bm-previous)
(global-set-key (kbd "M-]") 'bm-next)
(global-set-key (kbd "C-M-_") 'redo)
(global-set-key (kbd "C-c C-j") 'jaunte)
(global-set-key (kbd "M-S-u") 'upcase-previous-word)
(global-set-key (kbd "C-S-q") 'bury-buffer)
(global-set-key (kbd "C-c v") 'vcs)
(global-set-key (kbd "C-c C-w") 'alc)
