(global-set-key (kbd "C-,") 'other-window-or-split)
(global-set-key (kbd "C-<tab>") 'hs-toggle-hiding)
(global-set-key (kbd "C-M-_") 'redo)
(global-set-key (kbd "C-S-n") 'forward-paragraph)
(global-set-key (kbd "C-S-p") 'backward-paragraph)
(global-set-key (kbd "C-S-q") 'bury-buffer)
(global-set-key (kbd "C-c C-o") 'my-browse-at-point)
(global-set-key (kbd "C-c C-w") 'alc)
(global-set-key (kbd "C-c f") 'grep-find)
(global-set-key (kbd "C-c o") 'my-occur-current-word)
(global-set-key (kbd "C-c v") 'magit-status)
(global-set-key (kbd "C-h") 'my-delete-backward-char)
(global-set-key (kbd "M-L") 'downcase-previous-word)
(global-set-key (kbd "M-S-u") 'upcase-previous-word)
(global-set-key (kbd "M-SPC") 'bm-toggle)
(global-set-key (kbd "M-U") 'upcase-previous-word)
(global-set-key (kbd "M-[") 'bm-previous)
(global-set-key (kbd "M-]") 'bm-next)
(global-set-key (kbd "M-h") 'help)
(global-set-key (kbd "M-k") 'delete-line)
(global-set-key (kbd "M-m") 'memo)
(global-set-key (kbd "S-<down>") 'windmove-down)
(global-set-key (kbd "S-<left>") 'windmove-left)
(global-set-key (kbd "S-<right>") 'windmove-right)
(global-set-key (kbd "S-<up>") 'windmove-up)
(global-set-key (kbd "「") 'electric-pair)
(global-set-key (kbd "『") 'electric-pair)
(global-set-key (kbd "【") 'electric-pair)
(global-set-key [C-S-down] 'shrink-window)
(global-set-key [C-S-left] 'shrink-window-horizontally)
(global-set-key [C-S-right] 'enlarge-window-horizontally)
(global-set-key [C-S-up] 'enlarge-window)

(defalias 'o 'occur)
(defalias 'fg 'find-grep)
(defalias 'fnd 'find-name-dired)
