(add-hook 'sgml-mode-hook (lambda ()
                   (define-key html-mode-map (kbd "C-c C-j") 'jaunte)
                   (define-key sgml-mode-map "<" 'electric-pair)
                   (define-key sgml-mode-map "'" 'electric-pair)
                   (define-key sgml-mode-map "\"" 'electric-pair)
                   (setq sgml-basic-offset 4)))
(provide 'my-sgml-mode-config)
