(add-hook 'nxml-mode-hook 'zencoding-mode)
(add-hook 'sgml-mode-hook (lambda ()
                            (when  (require 'zencoding-mode nil t)
                              (zencoding-mode)
                              (define-key zencoding-mode-keymap (kbd "C-c C-m") 'zencoding-expand-line)
                              (define-key zencoding-preview-keymap (kbd "C-c C-m") 'zencoding-preview-accept))
                            (define-key html-mode-map (kbd "C-c C-j") 'jaunte)
                            (define-key sgml-mode-map "<" 'electric-pair)
                            (define-key sgml-mode-map "'" 'electric-pair)
                            (define-key sgml-mode-map "\"" 'electric-pair)
                            (setq sgml-basic-offset 4)))
(provide 'my-sgml-mode-config)
