#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from BeautifulSoup import BeautifulSoup

if __name__ == '__main__':
    input = sys.stdin.read()
    soup = BeautifulSoup(input)
    titles = [item.text for item in soup.ol("li")]
    for t in titles: print t


